globale:
  message: Welcome to customer Service dev environemnt
server: 
  port: 8082
message: Hello from Dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # options: validate | none | update | create | create-drop
    show-sql: true
