globale:
  message: Welcome to order Service prod environemnt
server: 
  port: 8085
message: Hello from order Prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # options: validate | none | update | create | create-drop
    show-sql: true
